//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class debts
    {
        public int id { get; set; }
        public string account { get; set; }
        public Nullable<decimal> debt { get; set; }
        public Nullable<decimal> paid { get; set; }
        public string datePayment { get; set; }
    }
}
